### ISSUE TITLE
axe (via pa11y) renvoie des erreurs sur le aria-hidden du web component

### ISSUE THREAD

**Issue by Lamecarlate** [joachimesque/en-ce-moment#109]
Le retour était assez cryptique :

``` js
 {
    code: 'aria-valid-attr-value',
    type: 'error',
    typeCode: 1,
    message: 'ARIA attributes must conform to valid values (https://dequeuniversity.com/rules/axe/4.8/aria-valid-attr-value?application=axeAPI)',
    context: '',
    selector: '',
    runner: 'axe',
    runnerExtras: {
      description: 'Ensures all ARIA attributes have valid values',
      impact: 'critical',
      help: 'ARIA attributes must conform to valid values',
      helpUrl: 'https://dequeuniversity.com/rules/axe/4.8/aria-valid-attr-value?application=axeAPI'
    }
  }
```
C'est sur ma page En ce moment, j'ai tenté d'enlever le web component du webring, et plus d'erreur. Je suppose que le souci remonté c'est qu'il y a des `aria-hidden` sans valeur.

De ce que je comprends des [spécifications de aria-hidden](https://w3c.github.io/aria/#aria-hidden), « pas de valeur » n'est pas une valeur autorisée. 

Je suggère donc d'écrire `aria-hidden="true"` au lieu de `aria-hidden` tout court.

**Comment by joachimesque** [comment]
Merci :)
J’ai fait la correction dans aa007bb494f587bcb7a6b80de7cd4baba96ecfb9, dis-moi si ça fonctionne !

**Comment by Lamecarlate** [comment]
Je viens d'écouter avec NVDA (je l'avais fait juste après avoir écrit ici et puis j'ai pas eu le courage de faire un enregistrement…), c'est nickel maintenant, on n'entend plus la description des emoji ! Je ferme, c'est OK pour moi.

**Comment by joachimesque** [comment]
Super, merci pour le signalement et les tests :)
